name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

permissions:
  contents: read
  packages: write
  issues: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Build
      id: build
      run: |
        make build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run
      id: run
      run: |
        make run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAILSERVER: ${{ secrets.MAILSERVER }}
        PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
        PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
